spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planetas_starwars
    driverClassName: org.postgresql.Driver
    username: hansolo
    password: 123456
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
